FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD streamlit run streamlit_user.py --server.port=${PORT:-8502} --server.address=0.0.0.0
