"""add type_mesure to recipe_ingredients

Revision ID: c801aa6cca01
Revises: da0d68c72424
Create Date: 2026-05-18 21:21:00.986360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c801aa6cca01'
down_revision: Union[str, Sequence[str], None] = 'da0d68c72424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('recipe_ingredients', sa.Column('type_mesure', sa.String(), nullable=True))
    op.execute("UPDATE recipe_ingredients SET type_mesure = 'poids' WHERE type_mesure IS NULL")
    op.alter_column('recipe_ingredients', 'type_mesure', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'type_mesure')
    # ### end Alembic commands ###
